version: "3"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-demo
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/rootpassword
    volumes:
      - ./neo4j/data:/data
